name: 'imp_poc'
version: '1.0.0'
config-version: 2

profile: 'imp_poc'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Hooks for dbt_artifacts (with dedicate schema)
on-run-start:
  - "CREATE SCHEMA IF NOT EXISTS {{ target.database }}.TECH"
  - "GRANT USAGE ON SCHEMA {{ target.database }}.TECH TO ROLE {{ target.role }}"
  - "GRANT CREATE TABLE ON SCHEMA {{ target.database }}.TECH TO ROLE {{ target.role }}"
  - "GRANT CREATE VIEW ON SCHEMA {{ target.database }}.TECH TO ROLE {{ target.role }}"
  - "{{ dbt_artifacts.upload_invocations() }}"
  
# Post-hooks: Run AFTER all models execute
on-run-end:
  - "{{ dbt_artifacts.upload_results(results) }}"
  - "{{ dbt_artifacts.upload_invocations() }}"

models:
  # Global project-level configurations
  +packages: ['pandas', 'numpy', 'scikit-learn', 'statsmodels']
  
  # dbt_artifacts package configuration
  dbt_artifacts:
    +schema: TECH
    +materialized: table
  
  # Your project structure
  imp_poc:
    staging:
      +materialized: view
    marts:
      +materialized: table